#ifndef aEwe2BLiT2_SIMPLE_HTTP_TYPE_METHOD_H
#define aEwe2BLiT2_SIMPLE_HTTP_TYPE_METHOD_H

/**
 * 
 */
typedef enum {
    METHOD_GET,
    METHOD_HEAD,
    METHOD_POST,
    METHOD_PUT,
    METHOD_DELETE,
    METHOD_CONNECTION,
    METHOD_OPTIONS,
    METHOD_TRACE,
    METHOD_PATCH
} Method;

#endif
